---
- hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Ensure Ansible dependencies are installed (CentOS 6).
      yum:
        name: libselinux-python
        state: present
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version | int == 6
    - name: Install some helpful utilities.
      apt:
        name:
          - wget
          - curl
          - vim
        state: present
      when: ansible_os_family == 'Debian'


  roles:
    - role: Geerlingguy.Nfs

    - role: packer-rhel
      when: ansible_os_family == 'RedHat'

    - role: packer-debian
      when: ansible_os_family == 'Debian'
    #- role: Xfce4desktop
