---
- src: git+http://gitea.johnpetro.xyz/ansible/packer-rhel.git
- src: git+http://gitea.johnpetro.xyz/ansible/packer-debian.git
- src: git+http://gitea.johnpetro.xyz/ansible/Geerlingguy.Nfs.git
- src: git+http://gitea.johnpetro.xyz/ansible/Xfce4desktop.git

